### ISSUE TITLE
creative can't read resources with illegal params

### ISSUE THREAD

**Issue by MelonHell** [unnamed/creative#20]
when i try to read the resource pack i get this error
```
java.lang.IllegalArgumentException: Invalid translation (Vector3Float{x=0.0f, y=-38.114296f, z=-81.24687f}), out of bounds (-80.0 to 80.0)
	at team.unnamed.creative.model.ItemTransform.validate(ItemTransform.java:98) ~[?:?]
	at team.unnamed.creative.model.ItemTransform.<init>(ItemTransform.java:91) ~[?:?]
	at team.unnamed.creative.model.ItemTransform.of(ItemTransform.java:204) ~[?:?]
	at team.unnamed.creative.serialize.minecraft.SerializerModel.readItemTransform(SerializerModel.java:381) ~[?:?]
	at team.unnamed.creative.serialize.minecraft.SerializerModel.readFromTree(SerializerModel.java:133) ~[?:?]
	at team.unnamed.creative.serialize.minecraft.MinecraftResourcePackReaderImpl.read(MinecraftResourcePackReaderImpl.java:175) ~[?:?]
	at team.unnamed.creative.serialize.minecraft.MinecraftResourcePackReader.readFromZipFile(MinecraftResourcePackReader.java:45) ~[?:?]
	at team.unnamed.creative.serialize.minecraft.MinecraftResourcePackReader.readFromZipFile(MinecraftResourcePackReader.java:52) ~[?:?]
	at ru.melonhell.resourcepackmerger.MergeService.merge(MergeService.kt:34) ~[ResourcePackMerger-1.0.0-SNAPSHOT.jar:?]
	at ru.melonhell.resourcepackmerger.MergeService.build(MergeService.kt:135) ~[ResourcePackMerger-1.0.0-SNAPSHOT.jar:?]
	at ru.melonhell.resourcepackmerger.Command.reload(Command.kt:21) ~[ResourcePackMerger-1.0.0-SNAPSHOT.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:757) ~[?:?]
	at cloud.commandframework.annotations.MethodCommandExecutionHandler.execute(MethodCommandExecutionHandler.java:79) ~[?:?]
	at cloud.commandframework.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$1(AsynchronousCommandExecutionCoordinator.java:101) ~[?:?]
	at cloud.commandframework.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$3(AsynchronousCommandExecutionCoordinator.java:131) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```
I understand that the resource pack contains incorrect data, but I would like to read it anyway

I can't manually change this resource pack as it is generated by another plugin

I would really like if you could add some flag that will allow you to read the resource pack ignoring errors or add custom error handlers so that I can write some kind of resolver for these errors at the read stage

**Comment by MelonHell** [comment]
I see three solutions to this problem:
1) add an ignore error flag, then I can read a bad resource pack and get a bad ItemTransform
2) add a flag to automatically correct such errors, then when reading a bad resource pack, bad values ​​will be cut off from -80 to 80
3) add some interface that will allow me to write custom logic for solving this problem

**Comment by yusshu** [comment]
I think it's better to \*not\* accept illegal params. As I wrote on #22, I think we should make the deserializer consistent with the Minecraft client, so that resource-packs that are invalid for it are also invalid for creative.
