### ISSUE TITLE
1.20 font parse error

### ISSUE THREAD

**Issue by MelonHell** [unnamed/creative#24]
```
java.lang.IllegalStateException: Unknown font provider type: reference
	at team.unnamed.creative.serialize.minecraft.SerializerFont.readFromTree(SerializerFont.java:96)
	at team.unnamed.creative.serialize.minecraft.MinecraftResourcePackReaderImpl.read(MinecraftResourcePackReaderImpl.java:233)
	at team.unnamed.creative.serialize.minecraft.MinecraftResourcePackReader.readFromZipFile(MinecraftResourcePackReader.java:45)
	at team.unnamed.creative.serialize.minecraft.MinecraftResourcePackReader.readFromZipFile(MinecraftResourcePackReader.java:52)
	at ResourcePackMerger-1.0.0-SNAPSHOT.jar//ru.melonhell.resourcepackmerger.MergeService.addFile(MergeService.kt:43)
	at ResourcePackMerger-1.0.0-SNAPSHOT.jar//ru.melonhell.resourcepackmerger.MergeService.merge(MergeService.kt:59)
	at ResourcePackMerger-1.0.0-SNAPSHOT.jar//ru.melonhell.resourcepackmerger.MergeService.build(MergeService.kt:168)
	at ResourcePackMerger-1.0.0-SNAPSHOT.jar//ru.melonhell.resourcepackmerger.PackReloadService.fullReload(PackReloadService.kt:14)
	at ResourcePackMerger-1.0.0-SNAPSHOT.jar//ru.melonhell.resourcepackmerger.Command.reload(Command.kt:18)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:757)
	at cloud.commandframework.annotations.MethodCommandExecutionHandler.execute(MethodCommandExecutionHandler.java:79)
	at cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95)
	at cloud.commandframework.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$1(AsynchronousCommandExecutionCoordinator.java:101)
	at cloud.commandframework.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$3(AsynchronousCommandExecutionCoordinator.java:131)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by dev-hydrogen** [comment]
related to #13
