### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by MelonHell** [unnamed/creative#31]
```
Caused by: java.lang.ClassCastException: class java.lang.Float cannot be cast to class java.lang.Double (java.lang.Float and java.lang.Double are in module java.base of loader 'bootstrap')
	at team.unnamed.creative.serialize.minecraft.model.ModelSerializer.writeItemOverride(ModelSerializer.java:366)
	at team.unnamed.creative.serialize.minecraft.model.ModelSerializer.serializeToJson(ModelSerializer.java:130)
	at team.unnamed.creative.serialize.minecraft.model.ModelSerializer.serializeToJson(ModelSerializer.java:61)
	at team.unnamed.creative.serialize.minecraft.io.JsonResourceSerializer.serialize(JsonResourceSerializer.java:42)
	at team.unnamed.creative.serialize.minecraft.MinecraftResourcePackWriterImpl.writeFullCategory(MinecraftResourcePackWriterImpl.java:64)
	at team.unnamed.creative.serialize.minecraft.MinecraftResourcePackWriterImpl.writeWithBasePath(MinecraftResourcePackWriterImpl.java:74)
	at team.unnamed.creative.serialize.minecraft.MinecraftResourcePackWriterImpl.write(MinecraftResourcePackWriterImpl.java:118)
	at team.unnamed.creative.serialize.minecraft.MinecraftResourcePackWriter.writeToZipFile(MinecraftResourcePackWriter.java:53)
	at team.unnamed.creative.serialize.minecraft.MinecraftResourcePackWriter.writeToZipFile(MinecraftResourcePackWriter.java:62)
```

https://github.com/unnamed/creative/blob/4ef71b431be91b25b5f974bc7fcb2bb87a3fa32e/serializer-minecraft/src/main/java/team/unnamed/creative/serialize/minecraft/model/ModelSerializer.java#L358

**Comment by yusshu** [comment]
Fixed 0b205c377938d865ce98765e6a9b0518e88e4263 (dev branch), fix will be available for creative `1.2.0`
